// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrbIQ0wPXpXMbNNDZMLX54A5LLAS8G57Q',
    appId: '1:263355054178:android:0f82c82e5962015f9e393b',
    messagingSenderId: '263355054178',
    projectId: 'amazingapp-8fcf1',
    storageBucket: 'amazingapp-8fcf1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMgUNwaccpNgoIjVpxTi9zoaZ93tG6ASM',
    appId: '1:263355054178:ios:fcbd17599d64dcf49e393b',
    messagingSenderId: '263355054178',
    projectId: 'amazingapp-8fcf1',
    storageBucket: 'amazingapp-8fcf1.appspot.com',
    androidClientId: '263355054178-id15eq112j85bcrtkpcgiu7kfnllctti.apps.googleusercontent.com',
    iosClientId: '263355054178-uhcu28d0pdb6d598an2ddj0n1gj3ofjd.apps.googleusercontent.com',
    iosBundleId: 'com.example.estateapp1',
  );
}
